function s = dsp__load_signals( folder )

props = { 'data', 'labels', 'fs', 'time' };

mats = dirstruct( folder, '.mat' );
names = { mats(:).name };

s = Structure();

while ( ~isempty(names) )
  current = names{1};
  underscores = strfind( current, '__' );
  assert( ~isempty(underscores), ...
    ['Attempting to call dsp__load_signals from files not generated by' ...
    , ' dsp__save_signals'] );
  ext = strfind( current, '.' );
  epoch = current( underscores+2:ext-1 );
  for i = 1:numel( props )
    to_load = sprintf( '%s__%s.mat', props{i}, epoch );
    load( fullfile(folder, to_load) );
    names( strcmp(names, to_load) ) = [];
  end
  obj = SignalObject( DataObject(data, labels), fs, time );
  s.(epoch) = obj;
end

end